server:
  port: 9098
spring:  datasource:    url: jdbc:mysql://localhost:3308/ies_dev
    username: root
    password: abcd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    properties:      hibernate:
        show-sql: true
        format-sql: true
    hibernate:      ddl-auto: update       